### ISSUE TITLE
GraalVM Enterprise support

### ISSUE THREAD

**Issue by mani1232** [RikoDEV/pterodactyl-graalvm#3]
add GraalVM Enterprise compact JDK container image.

**Comment by TH3N3WN00B** [comment]
Would love to see that

**Comment by RikoDEV** [comment]
Unfortunately, support for GraalVM Enterprise is not currently possible. Enterprise editions have a different license, which makes it impossible to make containers available on github.

You can download and build the Enterprise version yourself on a local server (which is supported by pterodactyl).

**Comment by TH3N3WN00B** [comment]
> Unfortunately, support for GraalVM Enterprise is not currently possible. Enterprise editions have a different license, which makes it impossible to make containers available on github.
> 
> You can download and build the Enterprise version yourself on a local server (which is supported by pterodactyl).

Got some links on how to do it?

**Comment by he3als** [comment]
Direct download links exist for GraalVM EE 17, 11 and 8 for Windows, Linux and MacOS. It should be possible to easily modify the `Dockerfile`s to use the EE links.

Credit: https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks

<details>
  <summary>Java 17</summary>

- Windows: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA17_22_3_0/graalvm-ee-java17-windows-amd64-22.3.0.zip
    
- Linux AMD64: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA17_22_3_0/graalvm-ee-java17-linux-amd64-22.3.0.tar.gz
    
- Linux ARM: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA17_22_3_0/graalvm-ee-java17-darwin-aarch64-22.3.0.tar.gz

- Mac AMD64: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA17_22_3_0/graalvm-ee-java17-darwin-amd64-22.3.0.tar.gz
    
</details>

<details>
  <summary>Java 11</summary>

- Windows: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA11_22_3_0/graalvm-ee-java11-windows-amd64-22.3.0.zip
    
- Linux AMD64: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA11_22_3_0/graalvm-ee-java11-linux-amd64-22.3.0.tar.gz
    
- Linux ARM: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA11_22_3_0/graalvm-ee-java11-darwin-aarch64-22.3.0.tar.gz

- Mac AMD64: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA11_22_3_0/graalvm-ee-java11-darwin-amd64-22.3.0.tar.gz
    
</details>

<details>
  <summary>Java 8</summary>

- Windows: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA8_21_3_4/graalvm-ee-java8-windows-amd64-21.3.4.zip
    
- Linux AMD64: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA8_21_3_4/graalvm-ee-java8-linux-amd64-21.3.4.tar.gz

- Mac AMD64: https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA8_21_3_4/graalvm-ee-java8-darwin-amd64-21.3.4.tar.gz
    
</details>

**Comment by he3als** [comment]
How would a pull request work for this? Would you only have to add new folders like `17-EE`, `11-EE` and `8-EE` for the PR (with the EE `Dockerfile`s and script) and that's it?

**Comment by RikoDEV** [comment]
> How would a pull request work for this? Would you only have to add new folders like `17-EE`, `11-EE` and `8-EE` for the PR (with the EE `Dockerfile`s and script) and that's it?

I think the EE suffix will be the most appropriate. Remember to add all folders to repo Actions too.

**Comment by he3als** [comment]
https://github.com/RikoDEV/pterodactyl-graalvm/pull/4 Made a PR

**Comment by RikoDEV** [comment]
Done! 🎉

> ghcr.io/rikodev/pterodactyl-graalvm:11-EE
> ghcr.io/rikodev/pterodactyl-graalvm:17-EE

Huge thanks to @he3als
