### ISSUE TITLE
Could not start a server with GraalVM EE Java 17

### ISSUE THREAD

**Issue by MrRaposinha** [RikoDEV/pterodactyl-graalvm#5]
### I don't know why, but I simply cannot start my server when I try to use GraalVM EE Java 17
`[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from rikodev/pterodactyl-graalvm 
Digest: sha256:5a0774602dbf4f6c26031b93124214e6f7b619f21e471ffe884551ee351fb4d0 
Status: Image is up to date for ghcr.io/rikodev/pterodactyl-graalvm:17-EE 
[Pterodactyl Daemon]: Finished pulling Docker container image
/entrypoint.sh: line 5: /opt/java/graalvm/bin/java: cannot execute binary file: Exec format error
:/home/container$ java -Xms8G -Xmx8G --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar server.jar --nogui
/entrypoint.sh: line 15: /opt/java/graalvm/bin/java: cannot execute binary file: Exec format error
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 126
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.`

**Comment by ytcalifax** [comment]
I seem to be having the very same issue, looks to be some issue with specifically the ARM-based version of the image. 

UPDATE: In case somebody sees this and needs ARM-based images before @RikoDEV updates this repo, I have created working ones [here](https://github.com/ytcalifax/pterodactyl-graalvm-ee).

**Comment by RikoDEV** [comment]
Hi @MrRaposinha & @ytcalifax
Sorry for the long wait to fix this error, everything should work in the latest images. The old Dockerfile was missing the TARGETPLATFORM variable, causing it to always download the version for amd64 processors instead of arm64.

![image](https://user-images.githubusercontent.com/18230443/236483908-ffe0eddc-9589-474e-801f-2d475e4f09d6.png)
