### ISSUE TITLE
GraalVM EE Can not display UTF-8 characters on the console.

### ISSUE THREAD

**Issue by kolderz** [RikoDEV/pterodactyl-graalvm#6]
It shows up as ? ? ? instead. I have -Dfile.encoding=UTF-8 startup flags.
Example: 
```啊啊啊 will show up as ???```

**Comment by RikoDEV** [comment]
Can you check the latest docker image?

**Comment by kolderz** [comment]
> Can you check the latest docker image?

it’s showing correctly now.
