### ISSUE TITLE
Oracle GraalVM for JDK 20.0.1

### ISSUE THREAD

**Issue by mani1232** [RikoDEV/pterodactyl-graalvm#8]
Changes: https://docs.oracle.com/en/graalvm/jdk/20/docs/release-notes/#oracle-graalvm-for-jdk-2001

FROM ghcr.io/graalvm/jdk-community:20.0.1

**Comment by RikoDEV** [comment]
Try `ghcr.io/rikodev/pterodactyl-graalvm:20-JDK`
